### ISSUE TITLE
Google Tag manager / Analytics on EPP client

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#104] opened 2022-10-10 08:10 UTC
Related: https://github.com/elifesciences/enhanced-preprints-server/issues/9

The EPP client does not have google analytics enabled. 

Definition of Done

- [x] GTM is appearing in the EPP HTML
- [x] Data for EPP staging and prod is appearing in GA
- [x] Hotjar can record a session

**Comment by de-code** [comment] 2022-10-14 14:09
Manual installation instructons:

> Below is the Google tag for this account. Copy and paste it in the code of every page of your website, immediately after the `<head>` element. Don’t add more than one Google tag to each page.

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-CTCHX4ZQV5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-CTCHX4ZQV5');
</script>
```

**Comment by de-code** [comment] 2022-10-14 14:37
Note: updated the above comment

**Comment by scottaubrey** [comment] 2022-10-17 08:29
@BlueReZZ @de-code This should be live for both environments now.

**Comment by BlueReZZ** [comment] 2022-10-17 08:36
Excellent, thank you.

@de-code is going to work on ensuring it is measuring correctly then look at specific measures detailed in https://github.com/elifesciences/data-hub-issues/issues/525

**Comment by scottaubrey** [comment] 2022-10-17 10:04
Sure - https://staging--epp.elifesciences.org/ and https://prod--epp.elifesciences.org/

**Comment by de-code** [comment] 2022-10-17 10:04
> Hi @scottaubrey could you please remind me of the URLs for staging and production?

Paul shared the links with me.

**Comment by de-code** [comment] 2022-10-17 14:42
For Cookiebot (not sure if you want to create it as a separate ticket), it seems to be just adding the following line as the **very first script** element:

```html
<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="0a5c50d8-fcf9-47b1-8f4f-1eaadb13941b" type="text/javascript"></script>
```

In this case staging and production seem to be using the same id (`0a5c50d8-fcf9-47b1-8f4f-1eaadb13941b`).


For more context, this is from the [Cookiebot Help](https://www.cookiebot.com/en/help/):

> **1. Cookie consent banner and widget:** Copy the top script and insert it as the **very first script** within the HEAD-tag of your website. Inserting it as the very first script ensures that no cookies or trackers escape our automatic cookie blocking. This script will guarantee that the banner is shown for consent collection and the widget is shown for consent changes and withdrawal. The Cookiebot CMP widget allows the user to withdraw (or change) their consent at any time – as required under e.g. GDPR. 
> 
> Example:
> 
> ```html
> <html>
> <head>
>   <script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="00000000-0000-0000-0000-000000000000" type="text/javascript". data-blockingmode="auto"></script>
> </head>
> <body>
>   ...
> </body>
> </html> 
> ```

**Comment by de-code** [comment] 2022-10-18 11:31
Thank you. I am looking at it now.

I believe you may still need to enable Cookiebot in the deployment config?

**Comment by de-code** [comment] 2022-10-18 11:36
It seems to be fixed in staging, but not yet in production? Was there a deployment issue?

**Comment by scottaubrey** [comment] 2022-10-18 11:51
Currently production isn't automated. I'll do the update there for you too

**Comment by scottaubrey** [comment] 2022-10-18 11:54
Update: it's now rolling out to prod. Also, cookiebot is in both.

**Comment by de-code** [comment] 2022-10-18 13:38
GTM seem to be working fine now.

For Cookiebot we would need to add the two domains as testing domains to the Cookiebot configuration.
@scottaubrey do you have access to do that?

**Comment by scottaubrey** [comment] 2022-10-18 14:33
I can, but I'm not sure how to handle it - I think we're expecting this to just come through the journal proxy, on elifesciences.org (and related domains). Does it work OK when accessed that way?

If not, should it be handled as an alias of elifesciences.org  or as a separate domain to the journal (like reviewer is)? 

Any thoughts @BlueReZZ ?

**Comment by BlueReZZ** [comment] 2022-10-18 14:46
If it's already set up for elifesiences.org and preview.elifesciences.org then it should be okay. I presume there's another testing.elifesciences.org or similar though (looking at GA) that might be needed.

It'll mean that @de-code needs to access it via those URLs rather than staging-- as he will have been doing.

Also, no harm in adding staging-- and prod-- as testing domains if the setting of the cookie and analytics still wire themselves up correctly for the testing required.

**Comment by scottaubrey** [comment] 2022-10-18 14:50
🤦 Sorry - here's the comment again:

I've added them as aliases (with the correct domain this time):

![Screenshot 2022-10-18 at 3 49 51 pm](https://user-images.githubusercontent.com/375812/196464791-de2becfc-f31d-4f21-95d6-5552b757c730.png)

**Comment by de-code** [comment] 2022-10-18 15:04
Thank you. This is mainly for me to test, that the integration works as intended before we publish it.

I am still getting Cookiebot complaining that the domain is not enabled. Has the change been published?

**Comment by de-code** [comment] 2022-10-18 15:06
Not sure whether `elifesciences.org` is maybe closer match (in terms of cookies used)? Although probably doesn't make much of a difference for this purpose.

**Comment by scottaubrey** [comment] 2022-10-18 16:12
Yeah, you're right, it should be an Ali's for elifesciences.org. I'll get it sorted pronto

**Comment by scottaubrey** [comment] 2022-10-18 16:15
Have, after all that I hadn't pressed save anyway! Should be there this time, I've refreshed cookiebot settings page to make sure this time!

**Comment by de-code** [comment] 2022-10-18 16:26
That is working well now. GTM still working with Cookiebot. I will do more testing and add more tracking. Chris can test Hotjar tomorrow too.

**Comment by de-code** [comment] 2022-10-18 17:04
Not to self:

For some reasons, Cookiebot's blocking of scripts does not seem to work. Not sure if it is due to being test version.

Cookies are removed after rejection. After reload I can still see Hotjar Cookies and Network requests for both Hotjar and GA.
For `https://continuumtest--journal.elifesciences.org/` the Hotjar cookies stay absent after rejection as expected and I do not see GA collect requests.

**Closed** 2022-11-08 10:06 UTC
